In [3]:
import numpy as np
from sklearn.model_selection import train_test_split

In [9]:
a = np.arange(1,100)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [13]:
b = np.arange(101, 200)
b

array([101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113,
       114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126,
       127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139,
       140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152,
       153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165,
       166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178,
       179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191,
       192, 193, 194, 195, 196, 197, 198, 199])

In [19]:
a_train, a_test = train_test_split(a)
a_train, a_test

(array([25, 96, 14, 32,  8, 49, 64, 71,  3, 38, 19, 44, 43, 79, 99,  2, 17,
         1, 66, 62,  6, 50, 70, 20, 34, 94, 72, 83, 33, 73, 41, 92, 86, 76,
        91, 21, 28, 69, 23, 60, 36, 97, 26, 30, 75, 46, 27, 95,  4, 87, 47,
        16, 37, 74, 13,  9, 39, 65, 67, 53, 15, 80, 78, 57,  7, 52, 11, 12,
        82, 81, 93, 55, 58, 61]),
 array([54, 42, 84, 56, 51, 88, 35, 59, 98, 63, 31,  5, 48, 77, 89, 10, 90,
        22, 85, 18, 40, 29, 24, 45, 68]))

In [21]:
b_train, b_test = train_test_split(b)
b_train, b_test

(array([111, 114, 141, 178, 143, 184, 107, 121, 117, 179, 182, 156, 194,
        181, 170, 180, 106, 153, 146, 198, 196, 105, 112, 130, 104, 175,
        154, 126, 189, 171, 177, 116, 102, 108, 197, 152, 161, 164, 120,
        132, 140, 138, 139, 148, 187, 190, 125, 158, 127, 128, 169, 147,
        131, 103, 157, 159, 101, 124, 165, 136, 134, 183, 113, 168, 122,
        115, 144, 193, 163, 172, 110, 155, 195, 191]),
 array([149, 167, 185, 129, 173, 142, 150, 176, 118, 166, 145, 135, 133,
        137, 109, 123, 162, 151, 160, 186, 192, 119, 174, 199, 188]))

In [23]:
a_train, a_test, b_train, b_test = train_test_split(a, b, random_state=42, test_size=0.2)

In [25]:
a_train, a_test, b_train, b_test

(array([50, 71, 69, 16, 40, 34, 10, 82, 12, 66, 95, 31, 29, 90,  6, 46, 70,
        36, 17, 73, 35,  8, 56, 28, 20, 81, 26, 54, 14, 25,  4, 18, 39,  9,
        78,  7, 80, 37, 92, 57, 99, 55, 44, 51, 67, 47, 68, 62, 97, 79, 42,
        59, 49, 86, 58, 76, 33, 94, 60, 64, 84, 38, 30,  2, 53, 22,  3, 24,
        88, 91, 75, 87, 83, 21, 61, 72, 15, 93, 52]),
 array([63, 41, 96, 19, 98, 85, 65, 43, 11,  1, 32, 77, 48, 27, 45,  5, 23,
        13, 89, 74]),
 array([150, 171, 169, 116, 140, 134, 110, 182, 112, 166, 195, 131, 129,
        190, 106, 146, 170, 136, 117, 173, 135, 108, 156, 128, 120, 181,
        126, 154, 114, 125, 104, 118, 139, 109, 178, 107, 180, 137, 192,
        157, 199, 155, 144, 151, 167, 147, 168, 162, 197, 179, 142, 159,
        149, 186, 158, 176, 133, 194, 160, 164, 184, 138, 130, 102, 153,
        122, 103, 124, 188, 191, 175, 187, 183, 121, 161, 172, 115, 193,
        152]),
 array([163, 141, 196, 119, 198, 185, 165, 143, 111, 101, 132, 177, 148,
        127, 145, 